"""
Scalekit AgentKit -- Gmail example (token path).

Generated by following the `integrating-agentkit` skill, Steps 1-4:
  1. Create a connected account for the user
  2. Have the user authorize the connection (OAuth)
  3. Fetch fresh OAuth tokens (Scalekit auto-refreshes them)
  4. Call the Gmail API with the access token as a Bearer token

Gmail works without any dashboard setup. For every OTHER connector, create
the connection in the Scalekit Dashboard first (AgentKit -> Connections ->
+ Create Connection) and set CONNECTION_NAME to its exact Connection Name.

Required env vars (see .env.example):
  SCALEKIT_ENVIRONMENT_URL, SCALEKIT_CLIENT_ID, SCALEKIT_CLIENT_SECRET
"""

import os

import requests
from dotenv import load_dotenv
from scalekit import ScalekitClient

load_dotenv()

# Exact dashboard Connection Name -- NOT a connector slug you invent.
CONNECTION_NAME = "gmail"
# Replace with your real application user id.
USER_IDENTIFIER = "user_123"

sk_client = ScalekitClient(
    client_id=os.getenv("SCALEKIT_CLIENT_ID"),
    client_secret=os.getenv("SCALEKIT_CLIENT_SECRET"),
    env_url=os.getenv("SCALEKIT_ENVIRONMENT_URL"),
)
actions = sk_client.actions


def ensure_authorized() -> None:
    """Steps 1-2: create the connected account and run OAuth if needed."""
    response = actions.get_or_create_connected_account(
        connection_name=CONNECTION_NAME,
        identifier=USER_IDENTIFIER,
    )
    connected_account = response.connected_account

    if connected_account.status != "ACTIVE":
        link_response = actions.get_authorization_link(
            connection_name=CONNECTION_NAME,
            identifier=USER_IDENTIFIER,
        )
        print("Authorize here:", link_response.link)
        input("Press Enter after authorizing...")


def get_access_token() -> str:
    """Step 3: re-fetch right before use so the token is always fresh."""
    response = actions.get_connected_account(
        connection_name=CONNECTION_NAME,
        identifier=USER_IDENTIFIER,
    )
    tokens = response.connected_account.authorization_details["oauth_token"]
    return tokens["access_token"]


def list_unread(access_token: str, max_results: int = 5) -> None:
    """Step 4: call Gmail with the OAuth access token."""
    headers = {"Authorization": f"Bearer {access_token}"}
    list_url = "https://gmail.googleapis.com/gmail/v1/users/me/messages"

    messages = (
        requests.get(
            list_url,
            headers=headers,
            params={"q": "is:unread", "maxResults": max_results},
        )
        .json()
        .get("messages", [])
    )

    for msg in messages:
        data = requests.get(
            f"{list_url}/{msg['id']}",
            headers=headers,
            params={
                "format": "metadata",
                "metadataHeaders": ["From", "Subject", "Date"],
            },
        ).json()
        hdrs = data.get("payload", {}).get("headers", [])
        subject = next((h["value"] for h in hdrs if h["name"] == "Subject"), "No Subject")
        sender = next((h["value"] for h in hdrs if h["name"] == "From"), "Unknown")
        print(subject)
        print(sender)
        print(data.get("snippet", ""))
        print("-" * 50)


if __name__ == "__main__":
    ensure_authorized()
    list_unread(get_access_token())
